# Site settings
author: Morgan VanYperen
title: Test Blog
header-img: img/home-bg.png
email: morgvanny@gmail.com
copyright_name: Morgan VanYperen
description: > # this means to ignore newlines until "baseurl:"
  Test Subtitle
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: morgvanny
github_username:  morgvanny

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
